### ISSUE TITLE
Missing package imports

### ISSUE THREAD

**Issue by Auhrus** [Alderon-Games/pot-community-servers#83] opened 2022-04-02 10:38 UTC
## Current Behavior
When the server is started, right at the beginning many such messages run through with different `0x390000AC` (`0x**0000**`) codes and different file paths/file names. But all of them revolve around the map Panjura.
## Expected Behavior
That the server starts without this messages. 🙃
## Crash Logs
(only a few examples entries are many more)
`LogStreaming: Warning: Missing package import 0x39000000AC for package /Game/Maps/Panjura/output/output_x04_y05`

`LogStreaming: Error: CreateExport: /Game/Maps/Panjura/output/output_x04_y05 (0x34B220732F14CF41) /Game/Maps/Panjura/output/output_x04_y05 (0x34B220732F14CF41) - Could not find template object for SceneCapture`

`LogStreaming: Warning: Missing package import 0x4B000000D9 for package /Game/Maps/Panjura/output/output_x07_y07`

`LogStreaming: Error: CreateExport: /Game/Maps/Panjura/output/output_x07_y07 (0x90CE4434D43BE95) /Game/Maps/Panjura/output/output_x07_y07 (0x90CE4434D43BE95) - Could not find template object for SceneCapture`
## Build Information

**Server Version:** 18338

**Operating System & Version:** Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0 x86_64)

**Comment by AlderonEmu** [comment] 2023-08-04 19:40
Closing as this issue is not a bug or will not be fixed.

**Closed as completed by AlderonEmu** 2023-08-04 19:40 UTC
