### ISSUE TITLE
Failed to find symbol file

### ISSUE THREAD

**Issue by Auhrus** [Alderon-Games/pot-community-servers#82] opened 2022-04-02 10:30 UTC
## Current Behavior
The server starts and after the output (as described in this issue #83 ) then comes this console output. There it hangs for about 1 minute and then it continues, but it does not generate the file or similar.
## Expected Behavior
That the server starts without this message (starts faster). 🙃
## Crash Logs
`Failed to find symbol file, expected location: "/opt/data/PathOfTitans/Binaries/Linux/PathOfTitansServer-Linux-Shipping.sym"`
## Build Information

**Server Version:** 18338

**Operating System & Version:** Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0 x86_64)

**Comment by AlderonEmu** [comment] 2023-08-04 19:40
Closing as this issue is not a bug or will not be fixed.

**Closed as completed by AlderonEmu** 2023-08-04 19:40 UTC
