### ISSUE TITLE
New stat: SwimmingStaminaConsumptionRate

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#77] opened 2022-02-16 05:09 UTC
I'm suggesting that there to be a stat that allows server owners to change how fast stamina drains while swimming for specific animals

**Comment by Paleocolour** [comment] 2022-04-19 08:10
This is called `StaminaSwimgCostPerSecond` `StaminaFastSwimCostPerSecond` `StaminaDiveCostPerSecond` `StaminaFastDiveCostPerSecond`

**Comment by Tyranid0548** [comment] 2022-05-24 05:35
Hey Paleo, Is the StaminaSwimgCostPerSecond supposed to have the g between Swim and Cost?

**Comment by Tyranid0548** [comment] 2022-05-29 03:30
Yeah these don't seem to be adjustable stats for us currently. @Paleocolour

**Comment by AlderonEmu** [comment] 2023-08-04 19:32
This has been forwarded to the QA team for review!

**Comment by AlderonEmu** [comment] 2023-10-06 14:00
Closing as this issue is not a bug or will not be fixed.

**Closed as completed by AlderonEmu** 2023-10-06 14:00 UTC
Labels: Type: New Feature, Status: Forwarded
