### ISSUE TITLE
Investigate Launch Parameters

### ISSUE THREAD

**Issue by ChrisPF123** [Alderon-Games/pot-community-servers#128] opened 2023-09-21 18:58 UTC
We need to see if theirs any server side launch parameters that might be coded in but not documented. 

We are looking to update our documentation for server administrators and want to know all launch parameters available to them.

**Comment by AlderonEmu** [comment] 2023-10-06 13:54
Closing as this issue is not a bug. Documentation is being updated and will be released in the future.

**Closed as completed by AlderonEmu** 2023-10-06 13:54 UTC
